Event/Controllers/EventManagement/GuestsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Event.Data.Objects.Entities;
using MyEventPlan.Data.DataContext.DataContext;
using MyEventPlan.Data.Service.AuthenticationManagement;
using MyEventPlan.Data.Service.EmailService;
using MyEventPlan.Data.Service.Enum;

namespace MyEventPlan.Controllers.EventManagement
{
    public class GuestsController : Controller
    {
        private readonly EventDataContext _databaseConnection = new EventDataContext();

        // GET: Guests
        [SessionExpire]
        public ActionResult Index()
        {
            var events = Session["event"] as Event.Data.Objects.Entities.Event;
            var guests =
                _databaseConnection.Guests.Where(n => n.EventId == events.EventId).Include(g => g.Event);
            return View(guests.ToList());
        }

        // GET: Guests/Details/5
        [SessionExpire]
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var guest = _databaseConnection.Guests.Find(id);
            if (guest == null)
                return HttpNotFound();
            return View(guest);
        }

        // GET: Guests/GuestAttending/5
        [SessionExpire]
        public ActionResult GuestAttending(long? id)
        {
            var guest = _databaseConnection.Guests.Find(id);
            guest.Status = GuestStatusEnum.Attending.ToString();
            _databaseConnection.Entry(guest).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Guests/GuestNotAttending/5
        [SessionExpire]
        public ActionResult GuestNotAttending(long? id)
        {
            var guest = _databaseConnection.Guests.Find(id);
            guest.Status = GuestStatusEnum.NotAttending.ToString();
            _databaseConnection.Entry(guest).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Guests/GuestAttending/5
        [SessionExpire]
        public ActionResult LoggedInGuestAttending(long? id)
        {
            var guest = _databaseConnection.Guests.Find(id);
            guest.Status = GuestStatusEnum.Attending.ToString();
            _databaseConnection.Entry(guest).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Guests/GuestNotAttending/5
        [SessionExpire]
        public ActionResult LoggedInGuestNotAttending(long? id)
        {
            var guest = _databaseConnection.Guests.Find(id);
            guest.Status = GuestStatusEnum.NotAttending.ToString();
            _databaseConnection.Entry(guest).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Guests/Create
        [SessionExpire]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Guests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Create([Bind(Include = "GuestId,Name,Email,PhoneNumber,EventId,GuestListId")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                guest.DateCreated = DateTime.Now;
                guest.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    guest.LastModifiedBy = loggedinuser.AppUserId;
                    guest.CreatedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.Guests.Add(guest);
                _databaseConnection.SaveChanges();

                var eventName = _databaseConnection.Event.Find(guest.EventId);
                new MailerDaemon().NewGuest(guest, eventName.Name);
                TempData["display"] = "You have successfully added the guest!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            return View(guest);
        }

        // GET: Guests/Edit/5
        [SessionExpire]
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var guest = _databaseConnection.Guests.Find(id);
            if (guest == null)
                return HttpNotFound();
            return View(guest);
        }

        // POST: Guests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Edit(
            [Bind(Include = "GuestId,Name,Email,PhoneNumber,EventId,GuestListId,EventPlannerId,CreatedBy,DateCreated")]
            Guest guest)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                guest.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    guest.LastModifiedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.Entry(guest).State = EntityState.Modified;
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully modified the guest!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            return View(guest);
        }

        // GET: Guests/Delete/5
        [SessionExpire]
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var guest = _databaseConnection.Guests.Find(id);
            if (guest == null)
                return HttpNotFound();
            return View(guest);
        }

        // POST: Guests/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult DeleteConfirmed(long id)
        {
            var guest = _databaseConnection.Guests.Find(id);
            _databaseConnection.Guests.Remove(guest);
            _databaseConnection.SaveChanges();
            TempData["guest"] = "You have successfully deleted the guest!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _databaseConnection.Dispose();
            base.Dispose(disposing);
        }
    }
}

Event/Views/Guests/Details.cshtml
@using Event.Data.Objects.Entities
@model Guest
@{
    ViewBag.Title = "View";
    Layout = "../Shared/Layout/_LayoutView.cshtml";
    ViewBag.TableHeader = Model.Name + " Guest Card";
    ViewBag.TableSubHeader = "Details of Guest";
    var events = Session["event"] as Event;
}
@section links{
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Events")">My Events</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Details", "Events", new {id = Model.EventId})">Event Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "GuestLists", new {eventId = Model.EventId})">Event Guest-Lists</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Guests", new {guestListId = Model.GuestListId})">Guest-List</a>
        </li>
    </ol>
}
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Event.Name)
    </dt>

    <dd>
        @if (events != null)
        {
            @events.Name
        }

    </dd>


    <dt>
        @Html.DisplayNameFor(model => model.GuestList.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.GuestList.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Email)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Email)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.PhoneNumber)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.PhoneNumber)
    </dd>
</dl>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary  fa fa-pencil" data-toggle="modal" data-target="#myModal">
    Edit Guest
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Edit Guest</h4>
            </div>
            <div class="modal-body">
                @{
                    Html.RenderPartial("EventPlanning/EditGuestModal", Model);
                }
            </div>
        </div>
    </div>

</div>
@Html.ActionLink("Attending Event", "GuestAttending", new {id = Model.GuestId}, new {@class = "btn btn-success  fa fa-check"})
@Html.ActionLink("Not Attending", "GuestNotAttending", new {id = Model.GuestId}, new {@class = "btn btn-danger  fa fa-off"})
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger  fa fa-trash" data-toggle="modal" data-target="#myModal1">
    Delete Guest
</button>

<!-- Modal -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel1">Delete Guest</h4>
            </div>@using (Html.BeginForm("Delete", "Guests", new {id = Model.GuestId}))
                  {
                      <div class="modal-body">

                          @Html.AntiForgeryToken()
                          <p>
                              Are you sure you want to remove the guest?
                          </p>

                      </div>
                      <div class="modal-footer">
                          <input type="submit" value="Remove" class="btn btn-danger pull-right fa fa-trash"/>
                          <input type="button" data-dismiss="modal" value="Cancel" class="btn btn-default pull-left"/>
                      </div>
                  }
        </div>
    </div>

</div>

Event/Views/Guests/Index.cshtml
@using Event.Data.Objects.Entities
@model IEnumerable<Guest>
@{
    ViewBag.Title = "List";
    ViewBag.TableHeader = "My Guests";
    ViewBag.TableSubHeader = "List of all event Attendees";
    Layout = "../Shared/Layout/_LayoutTable.cshtml";
    var guest = new Guest();
    var events = Session["event"] as Event;
}
@section links{
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Events")">My Events</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Details", "Events", new {id = events.EventId})">Event Dashboard</a>
        </li>
    </ol>
}
@section add {
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary  fa fa-plus pull-right" data-toggle="modal" data-target="#myModal">
        Add Guest
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Add a guest</h4>
                </div>
                <div class="modal-body">
                    @{
                        Html.RenderPartial("EventPlanning/CreateGuestModal", guest);
                    }
                </div>
            </div>
        </div>

    </div>
}
<div class="card-content table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Open", "Details", new {id = item.GuestId}, new {@class = "btn btn-default btn-lg fa fa-folder-open"})

                </td>
            </tr>
        }
        </tbody>
    </table>
</div>