Event/Controllers/EventManagement/CheckListItemsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Event.Data.Objects.Entities;
using MyEventPlan.Data.DataContext.DataContext;
using MyEventPlan.Data.Service.AuthenticationManagement;
using MyEventPlan.Data.Service.Calender;
using MyEventPlan.Data.Service.Enum;

namespace MyEventPlan.Controllers.EventManagement
{
    public class CheckListItemsController : Controller
    {
        private readonly EventDataContext _databaseConnection = new EventDataContext();

        // GET: CheckListItems
        [SessionExpire]
        public ActionResult Index(long? checkListId)
        {
            var checkListItems =
                _databaseConnection.CheckListItems.Where(n => n.CheckListId == checkListId)
                    .Include(c => c.CheckList)
                    .Include(c => c.Event);
            ViewBag.checkListId = checkListId;
            return View(checkListItems.ToList());
        }
        [HttpGet]
        public ActionResult ReloadItems(long? checkListId)
        {
            var checkListItems =
                _databaseConnection.CheckListItems.Where(n => n.CheckListId == checkListId)
                    .Include(c => c.CheckList)
                    .Include(c => c.Event);
            ViewBag.checkListId = checkListId;
            return PartialView("EventPlanning/CheckListItems", checkListItems.ToList());
        }
        // GET: CheckListItems/Details/5
        [SessionExpire]
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var checkListItem = _databaseConnection.CheckListItems.Find(id);
            if (checkListItem == null)
                return HttpNotFound();
            return View(checkListItem);
        }

        // GET: CheckItem
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult CheckItem(int[] table_records, FormCollection collectedValues)
        {
            var allMappings = _databaseConnection.CheckListItems.ToList();
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            var checkListId = Convert.ToInt64(collectedValues["checkListId"]);
            if (table_records != null)
            {
                var length = table_records.Length;
                for (var i = 0; i < length; i++)
                {
                    var id = table_records[i];
                    if (
                        allMappings.Any(
                            n =>
                                n.CheckListItemId == id &&
                                n.CheckListId == checkListId && n.Checked))
                    {
                    }
                    else
                    {
                        var item = _databaseConnection.CheckListItems.Find(id);
                        item.Checked = true;
                        item.DateLastModified = DateTime.Now;
                        if (loggedinuser != null) item.LastModifiedBy = loggedinuser.AppUserId;
                        _databaseConnection.Entry(item).State = EntityState.Modified;
                        _databaseConnection.SaveChanges();

                        var allItems = _databaseConnection.CheckListItems.Where(n => n.CheckListId == checkListId);
                        var checkList = _databaseConnection.CheckLists.Find(checkListId);
                        if (allItems.All(n => n.Checked))
                        {
                            checkList.Status = ChecklistStatusEnum.Completed.ToString();
                            _databaseConnection.Entry(checkList).State = EntityState.Modified;
                            _databaseConnection.SaveChanges();
                        }

                        TempData["display"] = "you have succesfully checked the item(s)!";
                        TempData["notificationtype"] = NotificationType.Success.ToString();
                    }
                }
            }
            else
            {
                TempData["display"] = "no item has been selected!";
                TempData["notificationtype"] = NotificationType.Error.ToString();
                return RedirectToAction("Index", new {checkListId});
            }
            return RedirectToAction("Index", new {checkListId});
        }

        // GET: CheckListItems/Create
        [SessionExpire]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckListItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Create(
            [Bind(Include = "CheckListItemId,Name,Checked,EventId,CheckListId")] CheckListItem checkListItem)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                checkListItem.DateCreated = DateTime.Now;
                checkListItem.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    checkListItem.LastModifiedBy = loggedinuser.AppUserId;
                    checkListItem.CreatedBy = loggedinuser.AppUserId;
                    checkListItem.Checked = false;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.CheckListItems.Add(checkListItem);
                _databaseConnection.SaveChanges();
                TempData["display"] = "Your have successfully created a new item!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
                return RedirectToAction("Index", new {checkListId = checkListItem.CheckListId});
            }
            return View(checkListItem);
        }
        public bool CreateMoreItems(string Name, string EventId, string CheckListId)
        {
            try
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                var items = new CheckListItem();
                items.Name = Name;
                items.CheckListId = Convert.ToInt64(CheckListId);
                items.EventId = Convert.ToInt64(EventId);
                items.DateCreated = DateTime.Now;
                items.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    items.CreatedBy = loggedinuser.AppUserId;
                    items.LastModifiedBy = loggedinuser.AppUserId;
                }

                _databaseConnection.CheckListItems.Add(items);
                _databaseConnection.SaveChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        // GET: CheckListItems/UncheckItem/5
        [SessionExpire]
        public ActionResult UncheckItem(long? id)
        {
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var checkListItem = _databaseConnection.CheckListItems.Find(id);
            if (checkListItem == null)
                return HttpNotFound();
            checkListItem.Checked = false;
            checkListItem.DateLastModified = DateTime.Now;
            if (loggedinuser != null) checkListItem.LastModifiedBy = loggedinuser.AppUserId;
            _databaseConnection.Entry(checkListItem).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            return RedirectToAction("Index", new {checkListId = checkListItem.CheckListId});
        }

        // GET: CheckListItems/Edit/5
        [SessionExpire]
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var checkListItem = _databaseConnection.CheckListItems.Find(id);
            if (checkListItem == null)
                return HttpNotFound();
            return View(checkListItem);
        }

        // POST: CheckListItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Edit(
            [Bind(Include = "CheckListItemId,Name,Checked,EventId,CheckListId,CreatedBy,DateCreated")] CheckListItem
                checkListItem)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                checkListItem.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    checkListItem.LastModifiedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.Entry(checkListItem).State = EntityState.Modified;
                _databaseConnection.SaveChanges();
                TempData["display"] = "Your have successfully modified the item!";

Event/Controllers/EventManagement/NotesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Event.Data.Objects.Entities;
using MyEventPlan.Data.DataContext.DataContext;
using MyEventPlan.Data.Service.AuthenticationManagement;
using MyEventPlan.Data.Service.Enum;

namespace MyEventPlan.Controllers.EventManagement
{
    public class NotesController : Controller
    {
        private readonly EventDataContext _databaseConnection = new EventDataContext();

        // GET: Notes
        [SessionExpire]
        public ActionResult Index(long? eventId)
        {
            var notes = _databaseConnection.Notes.Where(n => n.EventId == eventId).Include(n => n.Event);
            ViewBag.eventId = eventId;
            return View(notes.ToList());
        }

        // GET: Notes/Details/5
        [SessionExpire]
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var note = _databaseConnection.Notes.Find(id);
            if (note == null)
                return HttpNotFound();
            return View(note);
        }

        // GET: Notes/Create
        [SessionExpire]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Create([Bind(Include = "NoteId,Title,Content,ShowToClient,EventId")] Note note)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                note.DateCreated = DateTime.Now;
                note.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    note.LastModifiedBy = loggedinuser.AppUserId;
                    note.CreatedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.Notes.Add(note);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully added a built in note!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index", new {eventId = note.EventId});
            }
            return View(note);
        }

        // GET: Notes/Edit/5
        [SessionExpire]
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var note = _databaseConnection.Notes.Find(id);
            if (note == null)
                return HttpNotFound();
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Edit(
            [Bind(Include = "NoteId,Title,Content,ShowToClient,EventId,CreatedBy,DateCreated")] Note note)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                note.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    note.LastModifiedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.Entry(note).State = EntityState.Modified;
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully modified the built in note!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index", new {eventId = note.EventId});
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        [SessionExpire]
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var note = _databaseConnection.Notes.Find(id);
            if (note == null)
                return HttpNotFound();
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult DeleteConfirmed(long id)
        {
            var note = _databaseConnection.Notes.Find(id);
            var eventId = note.EventId;
            _databaseConnection.Notes.Remove(note);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully deleted the built in note!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index", new {eventId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _databaseConnection.Dispose();
            base.Dispose(disposing);
        }
    }
}

Event/Views/Shared/EventPlanning/AssignVendorToEvent.cshtml
@model Event.Data.Objects.Entities.EventVendorMapping
@{
    long? eventId = ViewBag.Event;
}
@using (Html.BeginForm("Create", "EventVendorMappings", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal row-fluid"}))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("EventId", eventId)

    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="form-group">
        @Html.LabelFor(model => model.VendorId, "VendorId", new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.DropDownList("VendorId", null, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.VendorId, "", new {@class = "text-danger"})
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Assign" class="btn btn-default"/>
        </div>
    </div>
}

Event/Views/Shared/EventPlanning/CheckListItems.cshtml
@using Event.Data.Objects.Entities
@using MyEventPlan.Data.DataContext.DataContext
@model IEnumerable<CheckListItem>
    @{
        var checkListItem = new CheckListItem();
        var db = new EventDataContext();
        long? listId = ViewBag.checkListId;
        var eventId = db.CheckLists.Find(listId).EventId;
    }
 <table class="table table-hover" id="grid">
    <thead>
    <tr>
        <th>
            <input type="checkbox" id="check-all" class="flat" onclick="toggle(this)">
        </th>
        <th>
           Name
         </th>

         <th>Action</th>
     </tr>
     </thead>
     <tbody>
     @foreach (var item in Model)
     {
         var allMappings = db.CheckListItems.SingleOrDefault(
             n =>
                 n.CheckListItemId == item.CheckListItemId &&
                 n.CheckListId == item.CheckListId && n.Checked);


         <tr>
             <td>
                 @if (allMappings != null)
                 {
                     <a href="@Url.Action("UncheckItem", "CheckListItems", new {id = item.CheckListItemId})">
                         <i class="fa fa-remove"></i>
                     </a>
                 }
                 else
                 {
                     <input type="checkbox" class="flat" name="table_records" value="@item.CheckListItemId">
                 }
             </td>

             <td>
                 @Html.DisplayFor(modelItem => item.Name)
             </td>

             <td>
                 @Html.ActionLink("Open", "Details", new {id = item.CheckListItemId}, new {@class = "btn btn-default btn-lg fa fa-folder-open"})
             </td>
         </tr>
     }
     </tbody>
 </table>

Event/Views/Shared/EventPlanning/CreateClientModal.cshtml
@model Event.Data.Objects.Entities.Client
@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
}
@using (Html.BeginForm("Create", "Clients", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="mui-textfield mui-textfield--float-label">
        @Html.LabelFor(model => model.Title, new { @class = "control-label" })

        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "span8", placeholder = "Enter client title" } })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
    </div>
    <div class="mui-textfield mui-textfield--float-label">
        @Html.LabelFor(model => model.Name, new { @class = "control-label" })

        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "span8", placeholder = "Enter client first name" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="mui-textfield mui-textfield--float-label">
        @Html.LabelFor(model => model.Email, new { @class = "control-label" })

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "span8", placeholder = "Enter client email address" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
    <div class="mui-textfield mui-textfield--float-label">
        @Html.LabelFor(model => model.Mobile, new { @class = "control-label" })

        @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "span8", placeholder = "Enter client mobile number" } })
        @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
    </div>
    <div class="form-control col-md-6">
        <input type="checkbox" name="LoginAccess" id="selector"/>
        @Html.Label("Generate Client Login?")
    </div>
    <div id="credential">
        <div class="mui-textfield mui-textfield--float-label">
            @Html.EditorFor(model => model.AccessEmail, new {htmlAttributes = new {placeholder = "Enter a access email"}})
            @Html.LabelFor(model => model.AccessEmail)
            @Html.ValidationMessageFor(model => model.AccessEmail, "", new {@class = "text-danger"})
        </div>
        <div class="mui-textfield mui-textfield--float-label">
            @Html.LabelFor(model => model.Password, new {@class = "control-label"})

            @Html.PasswordFor(model => model.Password, new {@class = "span8", placeholder = "Enter access password"})
            @Html.ValidationMessageFor(model => model.Password, "", new {@class = "text-danger"})
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Add Client" class="btn btn-default"/>
        </div>
    </div>
}
@section scripts{
    <script>
    
        $(document).ready(function () {
            $('#credential').hide();
            $('#selector').change(function(){
                if(this.checked)
                    $('#credential').fadeIn('slow');
                else
                    $('#credential').fadeOut('slow');

            });
        });
    </script> 
}

Event/Views/Shared/EventPlanning/CreateContactWebsiteModal.cshtml
@using MyEventPlan.Data.Service.Enum
@model Event.Data.Objects.Entities.ContactWebsite
@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
    long contactId = ViewBag.contactId;
}
@using (Html.BeginForm("Create", "ContactWebsites", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.Hidden("ContactId", contactId)
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="mui-select">
        @Html.DropDownListFor(m => m.Type, EnumHelper.GetSelectList(typeof(ContactWebsiteType)), "Select a type", new {@class = "", id = "selectFor"})
        @Html.ValidationMessageFor(model => model.Type, "", new {@class = "text-danger"})
    </div>
    <div class="mui-textfield mui-textfield--float-label">
        @Html.EditorFor(model => model.Website, new {htmlAttributes = new {placeholder = "Enter website"}})
        @Html.LabelFor(model => model.Website)
        @Html.ValidationMessageFor(model => model.Website, "", new {@class = "text-danger"})
    </div>

    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Add Website" class="btn btn-default"/>
        </div>
    </div>
}

Event/Views/Shared/EventPlanning/CreateInvoiceModal.cshtml
@model Event.Data.Objects.Entities.Invoice
@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
    long? eventId = ViewBag.id;
}
@section css{
    <link href="~/Scripts/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
}
@using (Html.BeginForm("Create", "Invoices", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("EventId", eventId)
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="mui-textfield mui-textfield--float-label">

        @Html.EditorFor(model => model.InvoiceName, new {htmlAttributes = new {placeholder = "Enter Invoice Name"}})
        @Html.LabelFor(model => model.InvoiceName)
        @Html.ValidationMessageFor(model => model.InvoiceName, "", new {@class = "text-danger"})
    </div>
    <div class="mui-textfield mui-textfield--float-label">
        @Html.EditorFor(model => model.InvoiceNumber, new {htmlAttributes = new {placeholder = "Enter Invoice Number"}})
        @Html.LabelFor(model => model.InvoiceNumber)
        @Html.ValidationMessageFor(model => model.InvoiceNumber, "", new {@class = "text-danger"})
    </div>
    <div class="mui-select">
        @Html.DropDownListFor(m => m.ClientId, (SelectList) ViewBag.ClientId, "Select the Client", new {@class = ""})
        @Html.ValidationMessageFor(model => model.ClientId, "", new {@class = "text-danger"})
    </div>
    <div class="mui-textfield mui-textfield--float-label">
        @Html.EditorFor(model => model.DueDate, new {htmlAttributes = new {@class = "span8 startDate", id = "datetimepicker5", placeholder = "Select Invoice Due Date"}})
        @Html.LabelFor(model => model.DueDate)
        @Html.ValidationMessageFor(model => model.DueDate, "", new {@class = "text-danger"})
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Add Invoice" class="btn btn-default"/>
        </div>
    </div>
}
<script src="~/Content/Dashboard/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">

    // init datepicker for date
    $('.startDate').datepicker({ 'startDate': new Date() });
</script>

Event/Views/Shared/EventPlanning/CreateMessageGroupMemeberModal.cshtml
@model Event.Data.Objects.Entities.MessageGroupMember
@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
    long? groupId = ViewBag.groupId;
}
@using (Html.BeginForm("Create", "MessageGroupMembers", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("MessageGroupId", groupId)
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})

    @Html.DropDownListFor(m => m.AppUserId, (SelectList) ViewBag.AppUserId, "Select the User", new {@class = ""})
    @Html.ValidationMessageFor(model => model.AppUserId, "", new {@class = "text-danger"})

    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Add Member" class="btn btn-default"/>
        </div>
    </div>
}

Event/Views/Shared/EventPlanning/CreateNews.cshtml
@model Event.Data.Objects.Entities.News

@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
}
@using (Html.BeginForm("Create", "News", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal row-fluid"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="control-group">
        @Html.LabelFor(model => model.Title, new {@class = "control-label"})
        <div class="controls">
            @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "span8"}})
            @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.Content, new {@class = "control-label"})
        <div class="controls">
            @Html.EditorFor(model => model.Content, new {htmlAttributes = new {@class = "span8"}})
            @Html.ValidationMessageFor(model => model.Content, "", new {@class = "text-danger"})
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.EventId, new {@class = "control-label"})
        <div class="controls">
            @Html.DropDownListFor(model => model.EventId, null, new {htmlAttributes = new {@class = "span8"}})
            @Html.ValidationMessageFor(model => model.EventId, "", new {@class = "text-danger"})
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.NewsImage, new {@class = "control-label"})
        <div class="controls">
            <input type="file" name="image" class="span8"/>
            @Html.ValidationMessageFor(model => model.NewsImage, "", new {@class = "text-danger"})
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Create List" class="btn btn-default"/>
        </div>
    </div>
}

Event/Views/Shared/EventPlanning/CreateNotesModal.cshtml
@model Event.Data.Objects.Entities.Note

@{
    long eventId = ViewBag.eventId;
}
@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
}
@using (Html.BeginForm("Create", "Notes", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("EventId", eventId)
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="mui-textfield mui-textfield--float-label">

        @Html.EditorFor(model => model.Title, new {htmlAttributes = new {placeholder = "Enter News Title"}})
        @Html.LabelFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
    </div>
    <div class="mui-textfield mui-textfield--float-label">

        @Html.TextAreaFor(model => model.Content, new {htmlAttributes = new {placeholder = "Enter News Contact"}})
        @Html.LabelFor(model => model.Content)
        @Html.ValidationMessageFor(model => model.Content, "", new {@class = "text-danger"})
    </div>
    <div class="mui-checkbox mui-checkbox--float-label">

        @Html.EditorFor(model => model.ShowToClient, new {htmlAttributes = new {placeholder = "Show to client?"}})
        @Html.LabelFor(model => model.ShowToClient)
        @Html.ValidationMessageFor(model => model.ShowToClient, "", new {@class = "text-danger"})
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Add Note" class="btn btn-default"/>
        </div>
    </div>
}

Event/Views/Shared/EventPlanning/CreatePersonalCheckListModal.cshtml
@model Event.Data.Objects.Entities.PersonalCheckList
@{
    Layout = "../../Shared/Layout/_LayoutModal.cshtml";
}
@using (Html.BeginForm("Create", "PersonalCheckLists", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="mui-textfield mui-textfield--float-label">

        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {placeholder = "Enter Check List Item Name"}})
        @Html.LabelFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Add List" class="btn btn-default"/>
        </div>
    </div>
}