Event/Controllers/EventManagement/EventResourceMappingsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Event.Data.Objects.Entities;
using MyEventPlan.Data.DataContext.DataContext;
using MyEventPlan.Data.Service.AuthenticationManagement;
using MyEventPlan.Data.Service.Enum;

namespace MyEventPlan.Controllers.EventManagement
{
    public class EventResourceMappingsController : Controller
    {
        private readonly EventDataContext _databaseConnection = new EventDataContext();

        // GET: EventResourceMappings
        [SessionExpire]
        public ActionResult Index()
        {
            var events = Session["event"] as Event.Data.Objects.Entities.Event;
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            var eventResourceMapping =
                _databaseConnection.EventResourceMapping.Where(n => n.EventId == events.EventId).Include(e => e.Event)
                    .Include(e => e.Resource);
            ViewBag.ResourceId = new SelectList(
                _databaseConnection.Resources.Where(n => n.EventPlannerId == loggedinuser.EventPlannerId), "ResourceId", "Name");
            return View(eventResourceMapping.ToList());
        }


        // GET: EventResourceMappings/Details/5
        [SessionExpire]
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var eventResourceMapping = _databaseConnection.EventResourceMapping.Find(id);
            if (eventResourceMapping == null)
                return HttpNotFound();
            return View(eventResourceMapping);
        }

        // GET: EventResourceMappings/Create
        [SessionExpire]
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventResourceMappings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Create(
            [Bind(Include = "EventResourceMappingId,EventId,ResourceId,Quantity")]
            EventResourceMapping eventResourceMapping)
        {
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                eventResourceMapping.DateCreated = DateTime.Now;
                eventResourceMapping.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    eventResourceMapping.CreatedBy = loggedinuser.AppUserId;
                    eventResourceMapping.LastModifiedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("Login", "Account");
                }
                var resourceId = eventResourceMapping.ResourceId;
                var resource = _databaseConnection.Resources.Find(resourceId);
                if (resource.Quantity > eventResourceMapping.Quantity)
                {
                    resource.Quantity = resource.Quantity - eventResourceMapping.Quantity;
                    resource.DateLastModified = DateTime.Now;
                    resource.LastModifiedBy = loggedinuser.AppUserId;
                }
                else
                {
                    TempData["display"] = "Your inventory does not have the quantity of resources required!";
                    TempData["notificationtype"] = NotificationType.Error.ToString();
                    return RedirectToAction("Index", new {eventId = eventResourceMapping.EventId});
                }
                _databaseConnection.Entry(resource).State = EntityState.Modified;
                _databaseConnection.EventResourceMapping.Add(eventResourceMapping);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully allocated the resource(s) to the event!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index", new {eventId = eventResourceMapping.EventId});
            }
            return View(eventResourceMapping);
        }

        // GET: EventResourceMappings/Edit/5
        [SessionExpire]
        public ActionResult Edit(long? id)
        {
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var eventResourceMapping = _databaseConnection.EventResourceMapping.Find(id);
            if (eventResourceMapping == null)
                return HttpNotFound();
            ViewBag.EventId = new SelectList(_databaseConnection.Event, "EventId", "Name", eventResourceMapping.EventId);
            ViewBag.ResourceId = new SelectList(
                _databaseConnection.Resources.Where(n => n.EventPlannerId == loggedinuser.EventPlannerId), "ResourceId", "Name",
                eventResourceMapping.ResourceId);
            return View(eventResourceMapping);
        }

        // POST: EventResourceMappings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Edit(
            [Bind(
                Include =
                    "EventResourceMappingId,EventId,ResourceId,CreatedBy,DateCreated,DateLastModified,LastModifiedBy")]
            EventResourceMapping eventResourceMapping)
        {
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                eventResourceMapping.DateLastModified = DateTime.Now;
                if (loggedinuser != null)
                {
                    eventResourceMapping.LastModifiedBy = loggedinuser.AppUserId;
                    var resourceId = eventResourceMapping.ResourceId;
                    var resource = _databaseConnection.Resources.Find(resourceId);
                    if (resource.Quantity > eventResourceMapping.Quantity)
                    {
                        resource.Quantity = resource.Quantity - eventResourceMapping.Quantity;
                        resource.DateLastModified = DateTime.Now;
                        resource.LastModifiedBy = loggedinuser.AppUserId;
                    }
                    else
                    {
                        TempData["display"] = "Your inventory does not have the quantity of resources required!";
                        TempData["notificationtype"] = NotificationType.Error.ToString();
                        return RedirectToAction("Index", new {eventId = eventResourceMapping.EventId});
                    }
                }
                else
                {
                    TempData["login"] = "Your session has expired, Login again!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("Login", "Account");
                }
                _databaseConnection.Entry(eventResourceMapping).State = EntityState.Modified;
                _databaseConnection.SaveChanges();
                TempData["resourcemap"] = "You have successfully added the resource to the event!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index", new {eventId = eventResourceMapping.EventId});
            }
            ViewBag.ResourceId = new SelectList(
                _databaseConnection.Resources.Where(n => n.EventPlannerId == loggedinuser.EventPlannerId), "ResourceId", "Name",
                eventResourceMapping.ResourceId);
            return View(eventResourceMapping);
        }

        // GET: EventResourceMappings/Delete/5
        [SessionExpire]
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var eventResourceMapping = _databaseConnection.EventResourceMapping.Find(id);
            if (eventResourceMapping == null)
                return HttpNotFound();
            return View(eventResourceMapping);
        }

        // POST: EventResourceMappings/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult DeleteConfirmed(long id)
        {
            var eventResourceMapping = _databaseConnection.EventResourceMapping.Find(id);

            if (eventResourceMapping != null)
            {
                var resourceId = eventResourceMapping.ResourceId;
                var resource = _databaseConnection.Resources.Find(resourceId);
                if (resource != null)
                {
                    resource.Quantity = resource.Quantity + eventResourceMapping.Quantity;
                    resource.DateLastModified = DateTime.Now;
                    eventResourceMapping.Quantity = 0;
                    _databaseConnection.Entry(resource).State = EntityState.Modified;
                    _databaseConnection.SaveChanges();
                }
            }
            _databaseConnection.EventResourceMapping.Remove(eventResourceMapping);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully deallocated the resources from the event!";
            TempData["notificationtype"] = NotificationType.Success.ToString();

Event/Views/EventResourceMappings/Create.cshtml
@model Event.Data.Objects.Entities.EventResourceMapping

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Create</title>
</head>
<body>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EventResourceMapping</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.EventId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceId, "ResourceId", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("ResourceId", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ResourceId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DateCreated, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateLastModified, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateLastModified, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DateLastModified, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedBy, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifiedBy, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastModifiedBy, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
</body>
</html>

Event/Views/EventResourceMappings/Delete.cshtml
@model Event.Data.Objects.Entities.EventResourceMapping

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Delete</title>
</head>
<body>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventResourceMapping</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Event.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resource.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resource.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateLastModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateLastModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedBy)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
</body>
</html>

Event/Views/EventResourceMappings/Details.cshtml
@using Event.Data.Objects.Entities
@model EventResourceMapping
@{
    ViewBag.Title = "View";
    ViewBag.Header = "View Allocated Resource";
    Layout = "../Shared/Layout/_LayoutForm.cshtml";
    var events = Session["event"] as Event;
}
@section links{
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Events")">My Events</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Details", "Events", new {id = Model.EventId})">Event Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "EventResourceMappings", new {eventId = Model.EventId})">Allocated Resources(s)</a>
        </li>
    </ol>
}
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Event.Name)
    </dt>

    <dd>
        @if (events != null)
        {
            @events.Name
        }

    </dd>
    <dt>
        @Html.DisplayName("Date Allocated")
    </dt>

    <dd>
        @Model.DateCreated.Date.ToString("d")
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Resource.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Resource.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Quantity)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Quantity)
    </dd>

</dl>
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger fa fa-trash" data-toggle="modal" data-target="#myModals1">
    Deallocate Resources
</button>

<!-- Modal -->
<div class="modal fade" id="myModals1" tabindex="-1" role="dialog" aria-labelledby="myModalLabels1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel1">Deallocate Resources</h4>
            </div>@using (Html.BeginForm("Delete", "EventResourceMappings", new {id = Model.EventResourceMappingId}))
                  {
                      <div class="modal-body">

                          @Html.AntiForgeryToken()
                          <p>
                              Are you sure you want to deallocate the resources from the event?

                          </p>

                      </div>
                      <div class="modal-footer">
                          <input type="submit" value="Deallocate" class="btn btn-danger pull-right fa fa-trash"/>
                          <input type="button" data-dismiss="modal" value="Cancel" class="btn btn-default pull-left"/>
                      </div>
                  }
        </div>
    </div>

</div>

Event/Views/EventResourceMappings/Edit.cshtml
@model Event.Data.Objects.Entities.EventResourceMapping

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Edit</title>
</head>
<body>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EventResourceMapping</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.EventResourceMappingId)

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.EventId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceId, "ResourceId", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("ResourceId", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ResourceId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DateCreated, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateLastModified, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateLastModified, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DateLastModified, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedBy, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifiedBy, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastModifiedBy, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
</body>
</html>

Event/Views/EventResourceMappings/Index.cshtml
@using Event.Data.Objects.Entities
@model IEnumerable<EventResourceMapping>
@{
    ViewBag.Title = "List";
    var events = Session["event"] as Event;
    ViewBag.TableHeader = "Resource Management";
    ViewBag.TableSubHeader = "Allocate Resources to " + events.Name + "";
    Layout = "../Shared/Layout/_LayoutTable.cshtml";
    var resourceEvent = new EventResourceMapping();
}
@section links{

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Events")">My Events</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@if (events != null)
                     {
                         @Url.Action("Details", "Events", new {id = events.EventId})
                     }">
                Event Dashboard
            </a>
        </li>
    </ol>
}
@section add {
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary  fa fa-plus pull-right" data-toggle="modal" data-target="#myModal">
        Allocate Resources
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Allocate Resources To Event</h4>
                </div>
                <div class="modal-body">
                    @{
                        Html.RenderPartial("EventPlanning/AssignResourcesToEvent", resourceEvent);
                    }
                </div>
            </div>
        </div>

    </div>
}
<div class="card-content table-responsive">
<table class="table table-hover" id="grid">
    <thead>
    <tr>
        <th>
            @Html.DisplayName("Date Allocated")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resource.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            Action
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.DateCreated.Date.ToString("d")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Resource.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.ActionLink("Open", "Details", new {id = item.EventResourceMappingId}, new {@class = "btn btn-default btn-lg fa fa-folder-open"})
            </td>
        </tr>
    }
    </tbody>
</table></div>