Event/Controllers/EventManagement/ContactAddressesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Event.Data.Objects.Entities;
using MyEventPlan.Data.DataContext.DataContext;
using MyEventPlan.Data.Service.AuthenticationManagement;
using MyEventPlan.Data.Service.Enum;

namespace MyEventPlan.Controllers.EventManagement
{
    public class ContactAddressesController : Controller
    {
        private EventDataContext db = new EventDataContext();

        // GET: ContactAddresses
        [SessionExpire]
        public ActionResult Index(long contactId)
        {
            ViewBag.contactId = contactId;
            var contactAddress = db.ContactAddress.Include(c => c.Contact).Where(n=>n.ContactId == contactId);
            return View(contactAddress.ToList());
        }

        // GET: ContactAddresses/Details/5
        [SessionExpire]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactAddress contactAddress = db.ContactAddress.Include(n=>n.Contact).SingleOrDefault(n=>n.ContactAddressId == id);
            if (contactAddress == null)
            {
                return HttpNotFound();
            }
            return View(contactAddress);
        }

        // GET: ContactAddresses/Create
        [SessionExpire]
        public ActionResult Create()
        {
            //ViewBag.ContactId = new SelectList(db.Contacts, "ContactId", "Title");
            return View();
        }

        // POST: ContactAddresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Create([Bind(Include = "ContactAddressId,Type,Street1,Street2,PostalCode," +
                                                   "State,Country,ContactId")] ContactAddress contactAddress,FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                contactAddress.Type = typeof(ContactAddressType).GetEnumName(int.Parse(collection["Type"]));
                contactAddress.Country = typeof(CountryEnum).GetEnumName(int.Parse(collection["Country"]));
                contactAddress.ContactId = Convert.ToInt64(collection["ContactId"]);
                db.ContactAddress.Add(contactAddress);
                db.SaveChanges();
                TempData["display"] = "You have successfully added a contact address!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index",new{ contactId  = contactAddress.ContactId});
            }

            ViewBag.ContactId = new SelectList(db.Contacts, "ContactId", "Title", contactAddress.ContactId);
            return View(contactAddress);
        }

        // GET: ContactAddresses/Edit/5
        [SessionExpire]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactAddress contactAddress = db.ContactAddress.Find(id);
            if (contactAddress == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContactId = new SelectList(db.Contacts, "ContactId", "Title", contactAddress.ContactId);
            return View(contactAddress);
        }

        // POST: ContactAddresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Edit([Bind(Include = "ContactAddressId,Type,Street1," +
                                                 "Street2,PostalCode,State,Country,ContactId")] ContactAddress contactAddress, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                contactAddress.Type = typeof(ContactAddressType).GetEnumName(int.Parse(collection["Type"]));
                contactAddress.Country = typeof(CountryEnum).GetEnumName(int.Parse(collection["Country"]));
                db.Entry(contactAddress).State = EntityState.Modified;
                db.SaveChanges();
                TempData["display"] = "You have successfully modified the contact address!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index", new { contactId = contactAddress.ContactId });
            }
            ViewBag.ContactId = new SelectList(db.Contacts, "ContactId", "Title", contactAddress.ContactId);
            return View(contactAddress);
        }

        // GET: ContactAddresses/Delete/5
        [SessionExpire]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactAddress contactAddress = db.ContactAddress.Find(id);
            if (contactAddress == null)
            {
                return HttpNotFound();
            }
            return View(contactAddress);
        }

        // POST: ContactAddresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult DeleteConfirmed(long id)
        {
            ContactAddress contactAddress = db.ContactAddress.Find(id);
            long contactId = (long) contactAddress.ContactId;
            db.ContactAddress.Remove(contactAddress);
            db.SaveChanges();
            TempData["display"] = "You have successfully deleted the website!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index", new {contactId });
        }
        [SessionExpire]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Event/Controllers/EventManagement/ContactsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Event.Data.Objects.Entities;
using MyEventPlan.Data.DataContext.DataContext;
using MyEventPlan.Data.Service.AuthenticationManagement;
using MyEventPlan.Data.Service.Enum;

namespace MyEventPlan.Controllers.EventManagement
{
    public class ContactsController : Controller
    {
        private readonly EventDataContext _databaseConnection = new EventDataContext();

        // GET: Contacts
        [SessionExpire]
        public ActionResult Index()
        {
            var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
            var contact =
                _databaseConnection.Contacts.Where(n => n.EventPlannerId == loggedinuser.EventPlannerId).Include(c => c.EventPlanner);
            return View(contact.ToList());
        }

        // GET: Contacts/Details/5
        [SessionExpire]
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var contact = _databaseConnection.Contacts.Find(id);
            if (contact == null)
                return HttpNotFound();
            return View(contact);
        }

        // GET: Contacts/Create
        [SessionExpire]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Create([Bind(Include = "ContactId,Title,Firstname,Lastname,Email,Mobile")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                if (loggedinuser != null) contact.EventPlannerId = loggedinuser.EventPlannerId;
                var contactExist = _databaseConnection.Contacts
                    .Where(m => m.Email == contact.Email && m.EventPlannerId == loggedinuser.EventPlannerId).ToList();
                if (loggedinuser != null)
                {
                    if (contactExist.Count > 0)
                    {
                        TempData["display"] = "A contact with the same email exist, try another email!";
                        TempData["notificationtype"] = NotificationType.Error.ToString();
                        return RedirectToAction("Index");
                    }
                    contact.CreatedBy = loggedinuser.AppUserId;
                    contact.DateCreated = DateTime.Now;
                    contact.DateLastModified = DateTime.Now;
                    contact.LastModifiedBy = loggedinuser.AppUserId;
                }
                _databaseConnection.Contacts.Add(contact);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully added a contact!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contacts/Edit/5
        [SessionExpire]
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var contact = _databaseConnection.Contacts.Find(id);
            if (contact == null)
                return HttpNotFound();
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult Edit(
            [Bind(Include = "ContactId,Title,Firstname,Lastname,Email,Mobile,EventPlannerId,CreatedBy,DateCreated")]
            Contact contact)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["myeventplanloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    contact.DateLastModified = DateTime.Now;
                    contact.LastModifiedBy = loggedinuser.AppUserId;
                }
                _databaseConnection.Contacts.Add(contact);
                _databaseConnection.SaveChanges();
                _databaseConnection.Entry(contact).State = EntityState.Modified;
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully modified the contact!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        [SessionExpire]
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var contact = _databaseConnection.Contacts.Find(id);
            if (contact == null)
                return HttpNotFound();
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SessionExpire]
        public ActionResult DeleteConfirmed(long id)
        {
            var contact = _databaseConnection.Contacts.Find(id);
            _databaseConnection.Contacts.Remove(contact);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully deleted the contact!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _databaseConnection.Dispose();
            base.Dispose(disposing);
        }
    }
}

Event/Views/ContactAddresses/Details.cshtml
@model Event.Data.Objects.Entities.ContactAddress
@{
    Layout = "../Shared/Layout/_LayoutView.cshtml";
    ViewBag.Title = "Details";
    ViewBag.TableHeader = "Contact Address";
    ViewBag.TableSubHeader = "Details of Contact Address";
}
@section links{

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Dashboard", "Home")">My Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Contacts")">Contacts</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "ContactAddresses",new{contactId = Model.ContactId})">Contact Address</a>
        </li>
    </ol>
}
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Contact Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact.DisplayName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary fa fa-pencil" data-toggle="modal" data-target="#myModal">
    Edit Address
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Edit contact address</h4>
            </div>
            <div class="modal-body">
                @{
                    Html.RenderPartial("EventPlanning/EditContactAddressModal", Model);
                }
            </div>
        </div>
    </div>

</div>
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger fa fa-trash" data-toggle="modal" data-target="#myModal1">
    Delete Address
</button>

<!-- Modal -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel1">Delete contact address</h4>
            </div>

            @using (Html.BeginForm("Delete", "ContactAddresses", new { id = Model.ContactAddressId }))
            {
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    <p>
                        Are you sure you want to remove the address?

                    </p>

                </div>
                <div class="modal-footer">
                    <input type="submit" value="Remove" class="btn btn-danger pull-right fa fa-trash" />
                    <input type="button" data-dismiss="modal" value="Cancel" class="btn btn-default pull-left" />
                </div>
            }
        </div>

    </div>
</div>

Event/Views/ContactAddresses/Index.cshtml
@using Event.Data.Objects.Entities
@model IEnumerable<ContactAddress>
@{
    ViewBag.Title = "List";
    ViewBag.TableHeader = "Contact Address";
    ViewBag.TableSubHeader = "List of all Contact addresses";
    Layout = "../Shared/Layout/_LayoutTable.cshtml";
    var contactAddress = new ContactAddress();
}

@section add {
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary  fa fa-plus pull-right" data-toggle="modal" data-target="#myModal">
        Add Address
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Add a new contact address</h4>
                </div>
                <div class="modal-body">
                    @{
                        Html.RenderPartial("EventPlanning/CreateContactAddressModal", contactAddress);
                    }
                </div>
            </div>
        </div>

    </div>

}
@section links{
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Contacts")">My Contacts</a>
        </li>
    </ol>
}
<div class="card-content table-responsive">
<table class="table table-hover" id="grid">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>
        </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.ActionLink("Open", "Details", new {id = item.ContactAddressId}, new {@class = "btn btn-lg btn-default fa fa-folder-open"})
        </td>
    </tr>
}
</tbody>
</table></div>